version: '3.8'

services:
  z36_server:
    build:
      context: ./server_python
      dockerfile: Dockerfile
    image: z36_server_image
    container_name: z36_server_container
    networks:
      z36_network:
        ipv4_address: 172.21.36.2
    ports:
      - "5018:5018/udp"

  z36_client:
    build:
      context: ./client_cpp
      dockerfile: Dockerfile
    image: z36_client_image
    container_name: z36_client_container
    networks:
      z36_network:
        ipv4_address: 172.21.36.3
    depends_on:
      - z36_server

networks:
  z36_network:
    external: true
