version: '3.8'

services:
  z36_server:
    build:
      context: ./server_python
      dockerfile: Dockerfile
    image: z36_server_image
    container_name: z36_server_container
    networks:
      z36_network:
        ipv4_address: 172.21.36.2
    ports:
      - "8080:8080/tcp"

  z36_client:
    build:
      context: ./client_python
      dockerfile: Dockerfile
    image: z36_client_image


networks:
  z36_network:
    external: true
